### PR TITLE
:bar_chart: migrate JSON data page for living planet index

### PR DESCRIPTION
**Pull request by Marigold**
Migrate [JSON-based Data page](https://owid.cloud/admin/grapher/global-living-planet-index) to [ETL-based Data page](http://staging-site-mojmir/admin/datapage-preview/811035) by adding metadata to its grapher step. I tried to match the original Data page as closely as possible, which means some metadata fields might not **adhere to our guidelines**. I moved [FAQs to its GDoc](https://docs.google.com/document/d/1gGburArxglFdHXeTLotFW4TOOLoeRq5XW6UfAdKtaAw/edit) and used official topic tags names.

@spoonerf could you please check the Data Page for any issues? You are also encouraged to update metadata in the YAML file according to guidelines. Commented lines are metadata from the ETL dataset, you should delete them if they're not helpful. **Add commits to this PR** as you wish!

You can test it by running
```
ENV=.env.mojmir etl living_planet_index --grapher
```
and visiting the [data page](http://staging-site-mojmir/admin/datapage-preview/811035).

### Known issues
* Only central estimate is shown (there's currently no way how to add other indicators)

Parent issue https://github.com/owid/etl/issues/1666

### CODE REVIEW

**Comment by spoonerf** [comment]
Thanks for migrating this @Marigold! 

Is it the case we cannot quite have the same formatting at the moment? I'm just wondering about the formatting for the section: "How does the producer of this data - WWF and Zoological Society of London - describe this data?"

I seemed to be able to add italics locally but not line-breaks. Just curious what the convention is at the moment. I'll add a commit to make it a bit clearer what I've tried!

**Comment by Marigold** [comment]
@spoonerf sorry for the late reply. As far as I know, italics should be done automatically (and line breaks fix) on the data page, but it's not ready yet. So I wouldn't worry about that. Just let me know if the metadata looks about right (it doesn't have to be perfect) and we'll get this merged.

**Comment by Marigold** [comment]
@spoonerf just give me green light when you think it's ok 🙏

**Comment by spoonerf** [comment]
@Marigold - sorry for the delay, it looks good to me!

**Review by spoonerf — APPROVED** [review]

**Pull request merged**
