### PR TITLE
:honeybee: catalog: typing

### PR DESCRIPTION
**Pull request by lucasrodes**

### CODE REVIEW

**Comment by Marigold** [comment]
@lucasrodes I spent some time trying to make it work, but with no success (even the simplest overriding of `__getitem__` didn't work). I'd close this and use `.loc[]` rather than square brackets. It's possible that pandas might fix that in their core code in the future.

**Comment by lucasrodes** [comment]
hey @Marigold, I think that makes sense for the `[]` issue. We could still add overloads for the other methods though.

**Comment by Marigold** [comment]
> I think we could still add overloads for the other methods though.

For sure. The question is whether to add them all at once or do it on the fly (which is what I'm doing). Some methods with a lot of arguments could end up having tons of `@overload` decorators.

**Comment by lucasrodes** [comment]
Alright, yeah, will be a long run.

Should we then try to push these changes or discard them for the time being?

**Comment by Marigold** [comment]
Sure, why not.

**Review by Marigold — APPROVED** [review]
Looks good.

**Comment by lucasrodes** [comment]
@Marigold still need to fix the tests not passing CI/CD. I'm looking at it.

**Review by Marigold — APPROVED** [review]
Looks good.

**Pull request merged**
