### PR TITLE
🐛  Fixing TB aggregates issue

### PR DESCRIPTION
**Pull request by spoonerf**

### CODE REVIEW

**Comment by spoonerf** [comment]
Hey @lucasrodes - hopefully this fixes the issue in https://github.com/owid/etl/pull/2884

**Review by lucasrodes — APPROVED** [review]
lgtm ー thanks!

**Review by lucasrodes — CHANGES_REQUESTED** [review]
Oops, just saw that the CI/CD is failing?

**Comment by spoonerf** [comment]
> Oops, just saw that the CI/CD is failing?

I think that is perhaps because of some other issue on the `load-dependency` branch. I did the PR from that, rather than master, but maybe I should have done it straight into master, what do you think?

**Comment by lucasrodes** [comment]
right ー that's true, good to go!

**Review by lucasrodes — APPROVED** [review]

**Pull request merged**
