### PR TITLE
:sparkles: Improve datadiff

### PR DESCRIPTION
**Pull request by Marigold**
Improve datadiff based on my experience with migrating to pandas 2.x. I've simplified the output, improved performance and handled edge cases.

There's also some prep for pandas 2.x migration to make the subsequent review easier.

## Datadiff

You can now use `etl diff dataset_path_a dataset_path_b` which use particularly useful for comparing versions. For instance
```
etl diff data/garden/climate/2024-01-31/sea_ice_index data/garden/climate/2024-03-11/sea_ice_index --verbose
```
The output has also changed. Instead of showing confusing "changed index" messages, I just show new/removed/updated values with a random sample of 5 values. For instance
```
 = Table sea_ice_index
    ~ Dim location
        + New values: 4 / 1084 (0.37%)
                date            location
          2024-01-15 Northern Hemisphere
          2024-02-15 Northern Hemisphere
          2024-01-15 Southern Hemisphere
          2024-02-15 Southern Hemisphere
    ~ Dim date
        + New values: 4 / 1084 (0.37%)
                     location       date
          Northern Hemisphere 2024-01-15
          Northern Hemisphere 2024-02-15
          Southern Hemisphere 2024-01-15
          Southern Hemisphere 2024-02-15
    ~ Column sea_ice_extent (changed metadata, new data)
        -     date_accessed: '2024-01-31'
        ?                            --
        +     date_accessed: '2024-03-11'
        ?                           ++
        -     date_published: '2024-01-30'
        ?                             --
        +     date_published: '2024-03-10'
        ?                            ++

        + New values: 4 / 1084 (0.37%)
                     location       date  sea_ice_extent
          Northern Hemisphere 2024-01-15          13.916
          Northern Hemisphere 2024-02-15          14.607
          Southern Hemisphere 2024-01-15           3.961
          Southern Hemisphere 2024-02-15           2.142
```
(dimensions are unnecessarily repeated twice, but the code would be less elegant if I fixed this minor issue)

Datadiff is still a work in progress, though. We can improve the output based on our needs in the future. (Having specific use cases would be useful)

## Pandas 2.x preps

* Add utility function for `read_sql` and call it instead of `pd.read_sql` (it silences warnings and creates connection from engine)
* Fix edge cases for repack

### CODE REVIEW

**Comment by pabloarosado** [comment]
Great work! Thanks for doing this. I think it would be good to update the documentation, since this new use case of comparing versions is not explained.

I tried the example you gave above and it worked well. However, I also tried `etl diff data/garden/faostat/2023-06-12/faostat_qcl data/garden/faostat/2024-03-14/faostat_qcl` and it printed at the end `No differences found`. But there clearly are differences between these two datasets. Maybe I'm misusing or misinterpreting something.

**Comment by pabloarosado** [comment]
Oh, I think what's happening is that the first step `data/garden/faostat/2023-06-12/faostat_qcl` is not found. I suppose it would be good to make this case clearer: "Step not found", instead of printing "No differences found".

**Review by pabloarosado — APPROVED** [review]
The code looks good, although I haven't looked carefully enough to be able to follow all the details. I tried it on some examples and works as expected. The only issue I found is that, as I mentioned before, if you pass two steps, and only one is found, the output is "No differences found" which can be misleading. But feel free to merge and we can fix that in a future PR.

**Comment by Marigold** [comment]
Good catch, fixed that. I'll add a section to docs when I finish all Datadiff changes that are planned.

**Pull request merged**
