### PR TITLE
:bar_chart: migrate JSON data page for objects in space

### PR DESCRIPTION
**Pull request by Marigold**
Migrate [JSON-based Data page](https://ourworldindata.org/grapher/yearly-number-of-objects-launched-into-outer-space) to [ETL-based Data page](http://staging-site-mojmir/admin/datapage-preview/814488) by adding metadata to its grapher step. I tried to match the original Data page as closely as possible, which means some metadata fields might not **adhere to our guidelines**. I moved [FAQs to its GDoc](https://docs.google.com/document/d/1gGburArxglFdHXeTLotFW4TOOLoeRq5XW6UfAdKtaAw/edit) and used official topic tags names.

@edomt do you want to review this yourself? If not, we can try asking @pabloarosado for help. You are also encouraged to update metadata in the YAML file according to guidelines. Commented lines are metadata from the ETL dataset, you should delete them if they're not helpful. **Add commits to this PR** as you wish!

You can test it by running
```
ENV=.env.mojmir etl un_space_objects --grapher
```
and visiting the [data page](http://staging-site-mojmir/admin/datapage-preview/814488).

Parent issue https://github.com/owid/etl/issues/1666

### CODE REVIEW

**Comment by edomt** [comment]
@Marigold What's the timeframe we're looking at here? My answer to whether I can do it, or someone else should do it, will depend a lot on that :)

**Comment by danyx23** [comment]
@edomt if possible we'd like to get these Prs ready to be merged this week

**Comment by edomt** [comment]
Thanks! Unlikely I'll be able to have a look then :(
@pabloarosado could you please have a look to ensure that everything looks fine? :)

**Comment by pabloarosado** [comment]
I've just updated the metadata. @edomt feel free to take a look at [the result](http://staging-site-migrate-space-objects/admin/datapage-preview/814488) if you have a few minutes.

On a seprate note, I worked on it from my local grapher, and found a bunch of data page issues. However, I suppose they are all currently been worked on. But I'll list them here for @danyx23 in case any of them was not known (otherwise ignore):
* Topic tags do not respect order.
* In the table, I see, e.g. Algeria 1 object launched in 1957, which is the closest point to 2002, where the object was actually launched. Given that there's no tolerance set, Algeria should simply not appear in any year except in 2002. The same happens for many other countries.
* The chart footer shows Producer, but it should show Producer (Year).
* The "Explore charts that include this data" section should not appear if there is only one chart.

**Comment by edomt** [comment]
Thank you @pabloarosado! 🙏🏻 

2 things I've spotted:

* The chart shows 2 decimal places, it should rather be 0
* In "How to cite this page" the chart is associated with the R&D page, but it should more likely be associated with the Space page. But maybe you're lacking a way to adjust that when the chart has multiple tags

**Review by pabloarosado — APPROVED** [review]

**Comment by danyx23** [comment]
Thanks a lot for reporting these issues, @pabloarosado!
- For the topic tag ordering, Mojmir has already created two PRs: https://github.com/owid/owid-grapher/pull/2858 and https://github.com/owid/etl/pull/1863
- The table display issue is worse than I thought. We just bumped this to priority 1, tracked here: https://github.com/owid/owid-grapher/issues/2831
- I'll fix the producer text logic
- The section below the chart is currently being redesigned by Sophia

**Comment by Marigold** [comment]
(Order of topic tags has been fixed.)

**Pull request merged**
