### PR TITLE
data(snapshot): add conflict datasets from spreadsheets

### PR DESCRIPTION
**Pull request by lucasrodes**
This PR adds several conflict datasets to Snapshot. To this end, I have created a new namespace: `conflicts`.

These datasets were previously manipulated and saved in [Google Drive](https://docs.google.com/spreadsheets/d/1lh4Ra3TaLt10ZRL4-C16--X1Zu4atofQO5iLwSBuOEY/edit#gid=1175422923). Here, we download these files from Google Drive and port them to Snapshots.

I have added [technical notes](https://docs.google.com/document/d/1aoBrW5UXkFNCZVM18teD9nYWcQH82_y5-uqeEH9c30E/edit#) to the corresponding dataset metadata.

### CODE REVIEW

**Review by pabloarosado — APPROVED** [review]
Hi @lucasrodes , I have a few comments/questions:
1. I'd suggest taking the `SNAPSHOT_VERSION` from `Path(__file__).parent.name`, to avoid hardcoding versions.
2. Couldn't you just use one script, called, e.g. "conflicts", which has a list of all `short_names` to process (assuming they all share the same version)?
3. I don't understand what file you are manually uploading each time (using `path-to-file`). I thought all data was in google documents.

Apart from that, it looks good.

**Comment by lucasrodes** [comment]
@pabloarosado, thanks for your feedback.

> 1. I'd suggest taking the `SNAPSHOT_VERSION` from `Path(__file__).parent.name`, to avoid hardcoding versions.
The `SNAPSHOT_VERSION` value was written by cookiecutter based on the parameters inputted during the `walkthrough` step. I think this is fine. I don't see a clear win here.


> 2. Couldn't you just use one script, called, e.g. "conflicts", which has a list of all `short_names` to process (assuming they all share the same version)?
Yes, that's an option. I preferred keeping them separate in case (i) versions for specific datasets change or (ii) we want to update specific datasets.

> 3. I don't understand what file you are manually uploading each time (using `path-to-file`). I thought all data was in google documents.

For each script, you will a URL to the file to be downloaded in the docstring. For instance, `sutton_1971.py` needs file at https://docs.google.com/spreadsheets/d/1Xo5e8aiFJnmv_aasFXU8MtzizSU0LxiysoUuErEJx3Q/edit?usp=sharing.

**Comment by pabloarosado** [comment]
> @pabloarosado, thanks for your feedback.
> 
> > 1. I'd suggest taking the `SNAPSHOT_VERSION` from `Path(__file__).parent.name`, to avoid hardcoding versions.
> 
> The `SNAPSHOT_VERSION` value was written by cookiecutter based on the parameters inputted during the `walkthrough` step. I think this is fine. I don't see a clear win here.

I think we should be moving in the direction of not having hardcoded versions in data steps. But as I mentioned in [the other PR](https://github.com/owid/etl/pull/756), we can look into this at another time.

> 
> > 2. Couldn't you just use one script, called, e.g. "conflicts", which has a list of all `short_names` to process (assuming they all share the same version)?
> 
> Yes, that's an option. I preferred keeping them separate in case (i) versions for specific datasets change or (ii) we want to update specific datasets.
> 
OK!

> > 3. I don't understand what file you are manually uploading each time (using `path-to-file`). I thought all data was in google documents.
> 
> For each script, you will a URL to the file to be downloaded in the docstring. For instance, `sutton_1971.py` needs file at https://docs.google.com/spreadsheets/d/1Xo5e8aiFJnmv_aasFXU8MtzizSU0LxiysoUuErEJx3Q/edit?usp=sharing.

I'm not sure I understood. So you have to manually download a file from google drive, and then input it via `--path-to-file`, is that right? If so, I think these instructions are not very clear in the docstring. And also, wouldn't it be possible to fetch the file directly from google drive? If you did it this way just for simplicity, maybe mention it in the docstring.

On a separate note, are the google drive files expected to be temporary, or to be maintained? I just checked the [sutton_1971](https://docs.google.com/spreadsheets/d/1Xo5e8aiFJnmv_aasFXU8MtzizSU0LxiysoUuErEJx3Q/edit?usp=sharing) file and its permissions are set to "Anybody with the link can edit". I supposed those permissions should be changed to read only.

**Comment by lucasrodes** [comment]
> I'm not sure I understood. So you have to manually download a file from google drive, and then input it via --path-to-file, is that right? If so, I think these instructions are not very clear in the docstring. And also, wouldn't it be possible to fetch the file directly from google drive? If you did it this way just for simplicity, maybe mention it in the docstring.

I tried making it more obvious in the docstrings, please let me know what you think. 

We could automatically download the files from Google Drive. I tried using `https://docs.google.com/spreadsheets/d/{key}/gviz/tq?tqx=out:csv` style link to download the file, but doesn't seem to work (some cells disappear). 

Instead, we could use `owid-datautils` in `Snapshot. download_from_source `, so that it could download google drive files, too.

https://github.com/owid/etl/blob/428066476d44fe0012334578816be38bf04e8482/etl/snapshot.py#L64-L68

> On a separate note, are the google drive files expected to be temporary, or to be maintained? I just checked the [sutton_1971](https://docs.google.com/spreadsheets/d/1Xo5e8aiFJnmv_aasFXU8MtzizSU0LxiysoUuErEJx3Q/edit?usp=sharing) file and its permissions are set to "Anybody with the link can edit". I supposed those permissions should be changed to read only.

Thanks for the catch. I changed the permissions!

**Comment by pabloarosado** [comment]
OK, if you think we will have to update these datasets often (more than once per year?), then it would be good if they could fetch data directly from google. Otherwise, a manual download is fine. Up to you!

**Pull request merged**
