### PR TITLE
fix 1444 removed code exactly as instructed here: /owid-grapher/pull/3792

### PR DESCRIPTION
**Pull request by toni-sharpe**
### fix 1444 removed code exactly

* instructions on [this PR](https://github.com/owid/owid-grapher/pull/3792) to keep things consistent were followed

### garden 1444 kept schemas consistent

* easy to revert if this is wrong

### CODE REVIEW

**Comment by danyx23** [comment]
The changes in your second commit don't make much sense. When one writes a json schema file, e.g. table.json that describes the schema of tables, this table.json can advertise that it adheres to a specific version of the json schema standard. Different files in one repo might legitimately adhere to different versions of the standard. You bumped the version numbers of these schemas by simply increasing the number but that doesn't make sense since e.g. draft 8 doesn't even exist: https://json-schema.org/specification#migrating-from-older-drafts

@toni-sharpe can you therefore please revert the second commit? You'll probably have to `git reset` to one changeset earlier and then force push your branch. Thanks!

**Review by danyx23 — CHANGES_REQUESTED** [review]
The changes in your second commit don't make much sense. When one writes a json schema file, e.g. table.json that describes the schema of tables, this table.json can advertise that it adheres to a specific version of the json schema standard. Different files in one repo might legitimately adhere to different versions of the standard. You bumped the version numbers of these schemas by simply increasing the number but that doesn't make sense since e.g. draft 8 doesn't even exist: https://json-schema.org/specification#migrating-from-older-drafts

@toni-sharpe can you therefore please revert the second commit? You'll probably have to git reset to one changeset earlier and then force push your branch. Thanks!

**Comment by toni-sharpe** [comment]
@danyx23 built to revert

**Comment by toni-sharpe** [comment]
@danyx23 a gap in my knowledge meant I misunderstood `git revert` and it hadn't removed the commit. Removed with `reset --hard` and I'll go read to see whay revert does exactly.

Hopefully this can now be merged

**Comment by danyx23** [comment]
@toni-sharpe looks good - I'll merge it when the other PR is ready to go

**Review by danyx23 — APPROVED** [review]
👍

**Comment by danyx23** [comment]
Thanks @toni-sharpe!

**Pull request merged**
