### PR TITLE
🎉 add a way to debug when having metadata issues

### PR DESCRIPTION
**Pull request by pabloarosado**
Possible fix for https://github.com/owid/etl/issues/1679

I was trying different things that didn't work. But I think this approach may be enough for now:

While working on an ETL step, manually define `Table.DEBUG = True`, and then:
* When running a line of code that creates a table column without an origin, a warning is raised.
* When displaying a table that has any column without an origin, a warning is raised.
* When loading a table that has indicators without origins, a warning is raised.

@Marigold please let me know if you have other ideas, thanks!

### CODE REVIEW

**Review by Marigold — APPROVED** [review]
Nice, let's give it a try! I wonder if we could use env variable `DEBUG` and have it turned on all the time when working locally (I haven't tried it, curious whether it'd be spamming me too much or not). Alternatively have both, but have Table.DEBUG default to environ.DEBUG.

**Comment by pabloarosado** [comment]
Hi @Marigold, thanks. Yes, I initially thought of using the DEBUG variable from .env (or creating another one called META_DEBUG). But then I realised that lib/catalog doesn't read from ETL .env, right?

**Comment by pabloarosado** [comment]
Also, @Marigold I was about to merge and noticed that CI was running 222 ETL steps. Is that expected? If so, I'd wait for the end of the day to merge this PR.

**Comment by Marigold** [comment]
> But then I realised that lib/catalog doesn't read from ETL .env, right?

Yes, exactly, I got confused by it at first, too. Perhaps we can just load it from `os.environ['DEBUG']`.

> I was about to merge and noticed that CI was running 222 ETL steps. Is that expected? If so, I'd wait for the end of the day to merge this PR.

It's unrelated, feel free to merge this. (I'm working on fixing ETL)

**Pull request merged**
