### PR TITLE
feat: delete files from remote in `sync_folder`

### LINKED ISSUE #55: Bug: Deleting files from DigitalOcean Spaces does not work
The `food_explorer` dataset at one point contained a file `grounut_oil.csv` (with a typo in the name), which was then deleted in subsequent versions.
However, [the file](https://owid-catalog.nyc3.digitaloceanspaces.com/garden/explorers/2021/food_explorer/grounut_oil.csv) is not properly deleted from the DigitalOcean bucket.

Below is the output of the _second_ run of `make publish`.
You can see that it correctly has `DEL garden/explorers/2021/food_explorer/grounut_oil.csv`, but doesn't include it in the `Datasets to delete` section.

```
owid@owid-live:~/etl$ make publish
==> Running full etl
.venv/bin/etl
Detecting which steps need rebuilding...
Running 1 steps:
1. data://garden/explorers/2021/food_explorer...
OK (149s)

==> Creating a catalog index
.venv/bin/reindex
==> Publishing the catalog
.venv/bin/publish
Datasets to sync:
- garden/explorers/2021/food_explorer
  PUT garden/explorers/2021/food_explorer/oranges.meta.json
  PUT garden/explorers/2021/food_explorer/string_beans.meta.json
  [...]
  PUT garden/explorers/2021/food_explorer/palm_fruit_oil.csv
  DEL garden/explorers/2021/food_explorer/grounut_oil.csv
  DEL garden/explorers/2021/food_explorer/grounut_oil.meta.json
Datasets to delete:
```

### PR DESCRIPTION
**Pull request by MarcelGerber**
Fixes #55.

⚠️ I haven't tried that this works at all, because I wouldn't even know how. But it _sounds_ reasonable.

### CODE REVIEW

**Comment by MarcelGerber** [comment]
btw, the test failures that we currently have are not our fault.
they are most likely related to an update of the GH Actions runners: https://github.com/actions/virtual-environments/issues/4733

**Review by larsyencken — APPROVED** [review]
Good catch, I totally forgot to code this case 😅

There was a formatting complaint which "make format" fixed, otherwise it passes "make test" locally which is good enough for us.

It's a real pain to test, since it won't revisit datasets that are already considered "synced" during "make publish".

I way we ship it and see.

**Comment by MarcelGerber** [comment]
> It's a real pain to test, since it won't revisit datasets that are already considered "synced" during "make publish".

yep, but the food explorer has enough updates right now that we should be able to see it in action soon.
The good thing is that `DEL` lines that `make publish` gives for the food explorer all make sense!

**Comment by MarcelGerber** [comment]
Fingers crossed 🤞

**Pull request merged**
