### PR TITLE
fix(food-explorer): improve heuristic for region metrics computation

### PR DESCRIPTION
**Pull request by lucasrodes**
This PR improves the heuristic for metric computation for regions. Details about the heuristic are explained in https://github.com/owid/owid-issues/issues/258.

Additionally, it makes sure that values for `Total` are always shown for all regions.

In the notebook, basically, section 9.5 is new. Note that the order of subsections 9.X has changed (e.g. 9.6 has been moved)

### CODE REVIEW

**Comment by marcelgerber** [comment]
Hm, it currently doesn't run

**Review by marcelgerber — CHANGES_REQUESTED** [review]
Hm, it currently fails for me with the following:
```
Exception encountered at "In [91]":
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_2180/3959191247.py in <module>
     16 values_to_remove = fe_bulk_melted_regions.loc[msk, "value"].unique()
     17 if not all(values_to_remove == [0.0, 0.011428571428571429]) or msk.sum() != 1512:
---> 18     raise ValueError("Re-check merge")
     19 # Filter NaNs (controlled)
     20 fe_bulk_melted_regions = fe_bulk_melted_regions[~msk]

ValueError: Re-check merge
```

**Comment by lucasrodes** [comment]
Thanks for the review @marcelgerber.

I just ran this `etl` locally and no error was raised:

```
.venv/bin/etl fbs          
Detecting which steps need rebuilding...
Running 3 steps:
1. data://meadow/faostat/2021-04-09/faostat_fbs...
OK (7s)

2. data://garden/faostat/2021-04-09/faostat_fbsc...
OK (62s)

3. data://garden/explorers/2021/food_explorer...
OK (164s)
```

I am now trying to think where the desync might be occurring, but not sure at the moment

**Comment by marcelgerber** [comment]
Hm, I ran it on `owid-analytics`, and you can try it there too:
```
ssh owid-analytics
cd etl-staging
.venv/bin/etl food_explorer
```

Maybe it's #76 again? Because you have different FAO API data locally than what is on `etl-staging` and my own machine (which are both pretty new installations of the etl)?

**Comment by lucasrodes** [comment]
I slightly relaxed the validation check, the ETL should run now.

There is a mismatch in the output between staging and my local machine. Hence I was not able to detect this error. This is due to some error in my local data files (at `~/.owid/walden`).

**Review by marcelgerber — APPROVED** [review]

**Pull request merged**
