### PR TITLE
data: Add US consumer prices

### PR DESCRIPTION
**Pull request by edomt**
Adds US consumer prices from the US Bureau of Labor Statistics (currently [here](https://owid.cloud/admin/datasets/566)).

### CODE REVIEW

**Comment by edomt** [comment]
@Marigold I'm getting the following error when running the garden step

```
Traceback (most recent call last):
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3803, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'CUUR0000SEEB01'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/edouard/git/etl/etl/run_python_step.py", line 34, in main
    _import_and_run(path, dest_dir)
  File "/Users/edouard/git/etl/etl/run_python_step.py", line 52, in _import_and_run
    module.run(dest_dir)
  File "/Users/edouard/git/etl/etl/steps/data/garden/bls/2023-03-10/us_consumer_prices.py", line 58, in run
    ds_garden = create_dataset(dest_dir, tables=[tb_garden], default_metadata=ds_meadow.metadata)
  File "/Users/edouard/git/etl/etl/helpers.py", line 126, in create_dataset
    ds.update_metadata(N.metadata_path)
  File "/Users/edouard/git/etl/vendor/owid-catalog-py/owid/catalog/datasets.py", line 163, in update_metadata
    table.update_metadata_from_yaml(metadata_path, table_name)
  File "/Users/edouard/git/etl/vendor/owid-catalog-py/owid/catalog/tables.py", line 437, in update_metadata_from_yaml
    setattr(self[v_short_name].metadata, k, v)
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/pandas/core/frame.py", line 3805, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/edouard/git/etl/.venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    raise KeyError(key) from err
KeyError: 'CUUR0000SEEB01'
```

Do you have any idea what could be wrong? I'm guessing I still haven't fully understood how metadata works.

**Comment by Marigold** [comment]
@edomt variable names need to be snake_case. We used to snak_case them explicitly, but now it's done automatically in `create_dataset` to get rid of boilerplate code. Sorry, there should be validation for that and linting rule for `*.meta.yml` file (adding asap).

Your YAML should look like this
```yaml
dataset: {}

tables:
  us_consumer_prices:
    variables:
      cuur0000seeb01:
        title: College tuition and fees
        description: College tuition and fees in U.S. city average, all urban consumers
      cuur0000sae1:
        title: Education
        description: Education in U.S. city average, all urban consumers
      cuur0000seeb:
        title: Tuition, other school fees, and childcare
        description: Tuition, other school fees, and childcare in U.S. city average, all urban consumers
      cuur0000sam:
        title: Medical care
        description: Medical care in U.S. city average, all urban consumers
      cuur0000sah21:
        title: Household energy
        description: Household energy in U.S. city average, all urban consumers
      cuur0000sah:
        title: Housing
        description: Housing in U.S. city average, all urban consumers
      cuur0000saf:
        title: Food and beverages
        description: Food and beverages in U.S. city average, all urban consumers
      cuus0000setg:
        title: Public transportation
        description: Public transportation in U.S. city average, all urban consumers
      cuus0000ss45011:
        title: New cars
        description: New cars in U.S. city average, all urban consumers
      cuur0000saa:
        title: Clothing
        description: Apparel in U.S. city average, all urban consumers
      cuur0000seee02:
        title: Computer software and accessories
        description: Computer software and accessories in U.S. city average, all urban consumers
      cuur0000sere01:
        title: Toys
        description: Toys in U.S. city average, all urban consumers
      cuur0000sera01:
        title: Televisions
        description: Televisions in U.S. city average, all urban consumers
```

**Comment by edomt** [comment]
Thank you @Marigold! All solved now. If you have time for a quick review, let me know if you see anything odd – but it should be another quick one.

**Comment by edomt** [comment]
@Marigold It seems my dataset made it to Grapher, but no the variables and data themselves: https://owid.cloud/admin/datasets/5920

Do you have any idea what I did wrong?

**Pull request merged**
