### PR TITLE
✨ wizard: new features

### PR DESCRIPTION
**Pull request by lucasrodes**
New sections under "Other tools":
- MetaGPT: GPT-based metadata assistance
- Dataset explorer: Explore dependencies of datasets visually

@veronikasamborska1994 
- As part of these enhancements, I've re-structured the ETL GPT tool by Veronika.
  - [x] `apps/metagpt/cli.py`
- Updated reference file:
  - [x] `snapshots/emissions/2023-11-23/national_contributions_annual_emissions.csv.dvc`
- Integrate ETL Meta GPT into wizard.
  - [x] Test it running `etl-wizard` and going to the ETL Meta GPT section

@Marigold 
- Just trying to plot a dependency graph. Try it with `etl-wizard` and navigate to "Dataset Explorer" section. I've used this tool: https://github.com/ChrisDelClea/streamlit-agraph, which is based on [visjs](https://visjs.github.io/vis-network/docs/network/) (same API)
  - [x] `apps/wizard/dataset_explorer.py`

### CODE REVIEW

**Comment by Marigold** [comment]
(Getting `ImportError: cannot import name '_to_graphviz' from 'etl.to_graphviz' (/Users/mojmir/projects/etl/etl/to_graphviz.py)`)

**Comment by lucasrodes** [comment]
@Marigold oops! good to go now

**Comment by veronikasamborska1994** [comment]
hey @lucasrodes!! thanks so much for refactoring the code! I've found a small issue with it - the code was asking chatGPT to generate a response 5 times irrespective of whether everything worked as expected on the first run or not. I've added a `return` statement to prevent this from happening. 

I am also getting an error when clicking on the etl metagpt option in wizard 

```
File "/Users/veronikasamborska/etl/.venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "/Users/veronikasamborska/etl/apps/wizard/metagpt.py", line 103, in <module>
    filepath = get_actual_path(cast(str, metadata_file))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/veronikasamborska/etl/apps/wizard/metagpt.py", line 84, in get_actual_path
    return path.replace(PREFIX_SNAPSHOT, PATH_SNAPSHOT).replace(PREFIX_GRAPHER, PATH_GRAPHER)
           ^^^^^^^^^^^^
```

**Review by veronikasamborska1994 — APPROVED** [review]
fyi looks like some unit tests are still failing

**Review by Marigold — APPROVED** [review]
I couldn't find a useful example for Dataset explorer, but I guess we can improve it over time. Code looks good.

By the way data://garden/faostat/2023-06-12/faostat_rl looks like corona

image

**Pull request merged**
