### PR TITLE
Combining SDG human rights variables

### PR DESCRIPTION
**Pull request by spoonerf**

### CODE REVIEW

**Review by paarriagadap — COMMENTED** [review]
Hi! Thanks, @spoonerf. I wanted to just run this to see the outcome on staging but I got this error (after a long running time):
```
2023-04-18 17:57.43 [info     ] upsert_table.uploaded_to_s3    size=2 variable_id=573894
2023-04-18 17:57:43,439 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "/Users/parriagadap/etl/.venv/bin/etl", line 6, in <module>
    sys.exit(main_cli())
             ^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/etl/command.py", line 119, in main_cli
    main(**kwargs)  # type: ignore
    ^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/etl/command.py", line 147, in main
    run_dag(
  File "/Users/parriagadap/etl/etl/command.py", line 245, in run_dag
    time_taken = timed_run(lambda: step.run())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/etl/command.py", line 252, in timed_run
    f()
  File "/Users/parriagadap/etl/etl/command.py", line 245, in <lambda>
    time_taken = timed_run(lambda: step.run())
                                   ^^^^^^^^^^
  File "/Users/parriagadap/etl/etl/steps/__init__.py", line 713, in run
    for table in dataset:
  File "/Users/parriagadap/etl/vendor/owid-catalog-py/owid/catalog/datasets.py", line 212, in __iter__
    yield self[name]
          ~~~~^^^^^^
  File "/Users/parriagadap/etl/vendor/owid-catalog-py/owid/catalog/datasets.py", line 117, in __getitem__
    raise KeyError(f"Table `{name}` not found, available tables: {', '.join(self.table_names)}")
KeyError: 'Table `_16_b_1__vc_vov_gdsd__no_breakdown_by_disability__language__or_dialect__all_areas__both_sexes` not found, available tables: '
```

I called the grapher table via owid catalog and I found this, which I am not sure it should be the outcome:
image

**Comment by spoonerf** [comment]
Hey @paarriagadap - it seemed to work for me on staging, here is the variable in question: https://staging.owid.cloud/admin/variables/588355

Let me know if you are happy with that and I'll merge

**Comment by paarriagadap** [comment]
> Is it all the 0 values that are unexpected for you in owid catalog? The four values at the top are what I would expect to be given.
Hi! Yes, all the zeros are unexpected. It's weird, because I also run this and I got what is expected:
image
Maybe I'm missing something about the structure of the dataset. But it seems to be working.

**Comment by spoonerf** [comment]
> > Is it all the 0 values that are unexpected for you in owid catalog? The four values at the top are what I would expect to be given.
> 
> Hi! Yes, all the zeros are unexpected. It's weird, because I also run this and I got what is expected: image Maybe I'm missing something about the structure of the dataset. But it seems to be working.

Strange - perhaps something to do with categorical data types. Either way, seems to be giving the desired variable so I'll merge now.

**Pull request merged**
