### PR TITLE
fix(wdi): save static copy of grapher metadata rather than dynamically fetching it

### PR DESCRIPTION
**Pull request by Marigold**
Fix for https://github.com/owid/etl/issues/442

Instead of fetching metadata dynamically we save it as feather file and load it at runtime. Minimal changes were made to `VariableMatcher`, it was pretty much just moved to its own file.

I've also considered using `.csv` for metadata, but it would have to be compressed to have small size. Feather seemed like an easier option in the end.

### CODE REVIEW

**Review by pabloarosado — COMMENTED** [review]
I see a 1.11MB feather file inside the steps folder, was that intentional?

**Comment by Marigold** [comment]
It contains metadata about variables ("backported" from grapher DB). Previously it was fetched dynamically from MySQL which wasn't ideal (others wouldn't be able to replicate it). An alternative is to have it in Walden S3 and get the data from there. Given that the file is only 1MB it's in my opinion not worth the hassle.

**Comment by pabloarosado** [comment]
> It contains metadata about variables ("backported" from grapher DB). Previously it was fetched dynamically from MySQL which wasn't ideal (others wouldn't be able to replicate it). An alternative is to have it in Walden S3 and get the data from there. Given that the file is only 1MB it's in my opinion not worth the hassle.

I see. But wouldn't it be better to actually load the backported grapher dataset, and work on it locally? Otherwise, this garden step depends on a grapher dataset (if I have understood correctly). If the grapher dataset changes over time, this step will return a different dataset, or fail.

**Comment by larsyencken** [comment]
It's only 1MB, but it's 1MB forever. The entire repo's only 40MB now, including all history, so it's still quite light.

I'm also wondering whether this is going to be a pattern for steps, so I want to understand how it was supposed to play out, to avoid future binary blobs in the ETL repo. I guess this metadata is also in a backported dataset, so it could be copied from there instead?

**Comment by Marigold** [comment]
Reduced file size to 600kb. Whitelisting only reduced it by 100kb and wasn't really worth it. Also moved everything to `wdi` folder to make it part of checksum.

**Review by larsyencken — APPROVED** [review]
Thanks Mojmir, fix linting and then it's good to ship

**Pull request merged**
