### PR TITLE
📊 OECD: exchange rates dataset

### PR DESCRIPTION
**Pull request by veronikasamborska1994**
for adjusting the unwto tourism (for inflation and/or cost of living) data later

### CODE REVIEW

**Review by Marigold — APPROVED** [review]
I checked some exchange rates of the final dataset and they look good (well, except of Argentina...). Just a heads up that we'll be updating WDI dataset this week, would it make any difference for you?

**Comment by veronikasamborska1994** [comment]
> I checked some exchange rates of the final dataset and they look good (well, except of Argentina...). Just a heads up that we'll be updating WDI dataset this week, would it make any difference for you?

thank you!! actually yep the PPP variable from the WDI will be useful for my AI updates and maybe some other charts on the tourism topic page as well :) but I don't think the WDI dataset has exchange rates, or does it?

**Comment by Marigold** [comment]
It doesn't. I just thought you might use newer `fp_cpi_totl` (CPI) from WDI, but probably not. Go ahead and merge this!

**Comment by veronikasamborska1994** [comment]
> It doesn't. I just thought you might use newer `fp_cpi_totl` (CPI) from WDI, but probably not. Go ahead and merge this!

thank you! :) ah yeah for this maybe it doesn't matter because the latest tourism data is 2021 but will definitely end up being useful for other things I am working on atm. will merge later tonight when I have a spare couple of hours to make sure it doesn't massively mess up the rest of my tourism charts. still scared of merging stuff haha :D

**Pull request merged**
