### PR TITLE
dataset(flu): Adding FluNet and FluID data for flu explorer

### PR DESCRIPTION
**Pull request by spoonerf**

### CODE REVIEW

**Comment by spoonerf** [comment]
Hey @Marigold,

I was hoping I could get your help on part of this. This is for the flu explorer which we spoke about in the data meeting the other day. I've used the `latest` version as I think that's what we need for it to be regularly updated? 

Also, when I run `poetry run etl data://garden/who/latest/fluid` it throws an error `FileNotFoundError: [Errno 2] No such file or directory: '/Users/fionaspooner/Documents/OWID/repos/etl/data/garden/who/latest/fluid/index.json'` and I can't figure out why. 

When I run `poetry run etl data://garden/who/latest/flunet` it works as expected. 

I'm planning to create a third dataset which combines `flunet` and `fluid` to feed into the explorer.

**Comment by Marigold** [comment]
> Also, when I run poetry run etl data://garden/who/latest/fluid it throws an error FileNotFoundError: [Errno 2] No such file or directory: '/Users/fionaspooner/Documents/OWID/repos/etl/data/garden/who/latest/fluid/index.json' and I can't figure out why.

Hmm, seems like something has failed when creating the dataset and `index.json` didn't get generated. Could you try removing it with `rm -Rf /Users/fionaspooner/Documents/OWID/repos/etl/data/garden/who/latest/fluid` and rerunning it again? (I'll see if I can replicate it and if yes I'll start throwing better error)

> I was hoping I could get your help on part of this. This is for the flu explorer which we spoke about in the data meeting the other day. I've used the latest version as I think that's what we need for it to be regularly updated?

Exactly. Regular update will involve running
1. `python snapshots/who/latest/fluid.py --skip-upload`
2. `python snapshots/who/latest/flunet.py --skip-upload`
3. then committing to master (and ETL will be run automatically)

We could do one such update manually and if it works I can automate it on our buildkite server.

**Comment by spoonerf** [comment]
> Could you try removing it with rm -Rf /Users/fionaspooner/Documents/OWID/repos/etl/data/garden/who/latest/fluid and rerunning it again? (I'll see if I can replicate it and if yes I'll start throwing better error)

That worked, thank you!

**Review by Marigold — APPROVED** [review]
Ran it locally and results looked good.

**Pull request merged**
