### PR TITLE
:bar_chart: migrate JSON data page for PIP indicators

### PR DESCRIPTION
**Pull request by Marigold**
Migrate JSON-based Data pages to ETL-based Data page by adding metadata to its grapher step. I tried to match the original Data page as closely as possible, which means some metadata fields might not **adhere to our guidelines**. I moved [FAQs to its GDoc](https://docs.google.com/document/d/1gGburArxglFdHXeTLotFW4TOOLoeRq5XW6UfAdKtaAw/edit) and used official topic tags names.

@paarriagadap  could you please check the Data Page for any issues? You are also encouraged to update metadata in the YAML file according to guidelines. Commented lines are metadata from the ETL dataset, you should delete them if they're not helpful. **Add commits to this PR** as you wish!

### Data pages
- [Extreme poverty JSON](https://ourworldindata.org/grapher/share-of-population-in-extreme-poverty) -> [Extreme poverty ETL](http://staging-site-mojmir/admin/datapage-preview/815270)
- [Below poverty line JSON](https://ourworldindata.org/grapher/relative-poverty-share-of-people-below-60-of-the-median) -> [Below poverty line ETL](http://staging-site-mojmir/admin/datapage-preview/815326)
- [Gini index JSON](https://ourworldindata.org/grapher/economic-inequality-gini-index) -> [Gini idex ETL](http://staging-site-mojmir/admin/datapage-preview/815324)

You can test it by running
```
ENV=.env.mojmir etl wb/2022-10-03/world_bank_pip --grapher
```
and opening [data pages from indicators](http://staging-site-mojmir/admin/datasets/6263)

### Known issues
* Two JSON-based data pages don't render as data pages any more. I'm not sure why

Parent issue https://github.com/owid/etl/issues/1666

### CODE REVIEW

**Comment by Marigold** [comment]
There's also Income of the 1% richest from WID

[JSON-based data page](https://ourworldindata.org/grapher/income-share-top-1-before-tax-wid) -> [ETL-based](http://staging-site-mojmir/admin/datapage-preview/811163)

Test it with
```
ENV=.env.mojmir GRAPHER_FILTER=p99p100_share_pretax etl wid/2023-08-24/world_inequality_database --grapher
```

**Comment by danyx23** [comment]
@Marigold the reason why some old style data pages don't render anymore is because we've updated the data and the charts so that the charts reference new variable ids but the datapage.json files in owid/owid-content/datapages still use the old variable ids as file numbers. I'm updating the ones mentioned here now, should be fixed after the next content bake

**Review by paarriagadap — APPROVED** [review]
Thank you, @Marigold! I have included my changes.

I am currently in this (longer than expected) [update of the PIP data](https://github.com/owid/etl/pull/1505) and this will be very useful to define the metadata in this new format. In the future I will migrate with a WID and LIS update as well.

I have a problem with PIP, I can't push this Grapher step:
```
(etl-py3.11) parriagadap@Pablos-MacBook-Pro etl % ENV=.env.parriagadap etl wb/2022-10-03/world_bank_pip --grapher                                                
--- Detecting which steps need rebuilding...
OK (0.3s)                                                             
--- Running 2 steps:
--- 1. data://grapher/wb/2022-10-03/world_bank_pip...
2023-10-18 16:48:31,952 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/etl/run_python_step.py", line 34, in main
    _import_and_run(path, dest_dir)
  File "/Users/parriagadap/etl/etl/run_python_step.py", line 54, in _import_and_run
    module.run(dest_dir)
  File "/Users/parriagadap/etl/etl/steps/data/grapher/wb/2022-10-03/world_bank_pip.py", line 23, in run
    ds_grapher = create_dataset(dest_dir, tables=[tb], default_metadata=ds_garden.metadata)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/etl/helpers.py", line 188, in create_dataset
    ds.update_metadata(meta_path, if_origins_exist=if_origins_exist)
  File "/Users/parriagadap/etl/lib/catalog/owid/catalog/datasets.py", line 212, in update_metadata
    table.update_metadata_from_yaml(metadata_path, table_name, if_origins_exist=if_origins_exist)
  File "/Users/parriagadap/etl/lib/catalog/owid/catalog/tables.py", line 506, in update_metadata_from_yaml
    return update_metadata_from_yaml(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/lib/catalog/owid/catalog/yaml_metadata.py", line 34, in update_metadata_from_yaml
    annot = dynamic_yaml_to_dict(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/lib/catalog/owid/catalog/utils.py", line 197, in dynamic_yaml_to_dict
    return yaml.safe_load(dynamic_yaml.dump(yd))
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/dynamic_yaml/__init__.py", line 44, in dump
    return yaml.dump(data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/yaml/__init__.py", line 253, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/yaml/__init__.py", line 241, in dump_all
    dumper.represent(data)
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/dynamic_yaml/__init__.py", line 22, in _represent_dynamic_yaml_dict
    return dumper.represent_mapping(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/dynamic_yaml/__init__.py", line 22, in _represent_dynamic_yaml_dict
    return dumper.represent_mapping(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/dynamic_yaml/__init__.py", line 22, in _represent_dynamic_yaml_dict
    return dumper.represent_mapping(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/dynamic_yaml/__init__.py", line 22, in _represent_dynamic_yaml_dict
    return dumper.represent_mapping(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/dynamic_yaml/__init__.py", line 23, in _represent_dynamic_yaml_dict
    yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, {key: data[key] for key in data._collection}
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/dynamic_yaml/__init__.py", line 23, in <dictcomp>
    yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, {key: data[key] for key in data._collection}
                                                          ~~~~^^^^^
  File "/Users/parriagadap/etl/.venv/lib/python3.11/site-packages/dynamic_yaml/yaml_wrappers.py", line 26, in __getitem__
    value = value.format(**super().__getattribute__("_root")._collection)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'common'

COMMAND: poetry run run_python_step data://grapher/wb/2022-10-03/world_bank_pip /Users/parriagadap/etl/data/grapher/wb/2022-10-03/world_bank_pip
```

**Comment by Marigold** [comment]
Thanks a lot @paarriagadap, that's a really hefty commit :). Merging this now!

> I have a problem with PIP, I can't push this Grapher step:

The branch is a bit outdated. It'll work fine after merging.

**Pull request merged**
