### PR TITLE
:tada: allow placeholders in metadata yaml files

### PR DESCRIPTION
**Pull request by Marigold**
Use `dynamic_yaml` library to enable placeholders in YAML files. I've only tried it for two minor examples - [DRYing descriptions](https://github.com/owid/etl/compare/covid-google-mobility-trends...791-allow-placeholders-in-metadata-yaml-files?expand=1#diff-ddc1416f62619b0f3588bc84ab5a31fe67581d866838cd9cee07cce9a2117bcaR174) and adding date parameter.

I'm a bit hesitant to merge this, better wait for a use case where this will be helpful. @pabloarosado @paarriagadap if you run into such use case, please let me know and I'll polish this and merge.

### CODE REVIEW

**Review by pabloarosado — APPROVED** [review]
This looks good. I think the TODAY case is only used in covid. In most cases what we'd need is a YEAR field. This could be extracted from the version, which is included in the `path`.

**Comment by Marigold** [comment]
Thanks Pablo! Added `YEAR` too, though it still needs to be tested on a real dataset.

**Comment by paarriagadap** [comment]
Hi @Marigold! Looks interesting. I wanted to try it in the example you changed (`ethinc_power_relations`), but I found the `ModuleNotFoundError: No module named 'dynamic_yaml'` error;

```
(etl-py3.11) parriagadap@Pablos-MacBook-Pro etl % etl ethnic    
2023-06-19 11:21:22,237 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "/Users/parriagadap/etl/.venv/bin/etl", line 3, in <module>
    from etl.command import main_cli
  File "/Users/parriagadap/etl/etl/command.py", line 17, in <module>
    from etl.snapshot import snapshot_catalog
  File "/Users/parriagadap/etl/etl/snapshot.py", line 16, in <module>
    from owid.catalog.meta import pruned_json
  File "/Users/parriagadap/etl/lib/catalog/owid/catalog/__init__.py", line 3, in <module>
    from . import utils
  File "/Users/parriagadap/etl/lib/catalog/owid/catalog/utils.py", line 6, in <module>
    import dynamic_yaml
ModuleNotFoundError: No module named 'dynamic_yaml'
```

Is it OK to install it on my own (`pip install dynamic-yaml`) or do you prefer to have it inside the environment?

**Comment by paarriagadap** [comment]
Well, I installed and it seems to be [working as expected](https://staging.owid.cloud/admin/variables/576844)! The structure should be always starting by `|-` and in the (indented) next like proceed just like when there are `|` in non-placeholdered text, right?

**Comment by Marigold** [comment]
Thanks for trying it out @paarriagadap. You have to run `poetry install` to get `dynamic_yaml` package (or perhaps it's not as simple?)

`|-` works the same as `|` but it strips new lines. If you used
```
group_relevance: |
    An ethnic group is deemed relevant in a given group-year if at least one political organization claims to represent it in national politics or if its members are subjected to state-led political discrimination.
    
```
you'd get newline at the beginning at at the end and you'd get weird newlines when using them as placeholders. It's up to you whether you use it or not.

**Comment by paarriagadap** [comment]
@Marigold I tried `poetry install` and failed; that's why I decided to go with pip install anyway
```
(etl-py3.11) parriagadap@Pablos-MacBook-Pro etl % poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: etl (0.1.0)
(etl-py3.11) parriagadap@Pablos-MacBook-Pro etl % etl ethnic    
2023-06-19 11:21:22,237 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "/Users/parriagadap/etl/.venv/bin/etl", line 3, in <module>
    from etl.command import main_cli
  File "/Users/parriagadap/etl/etl/command.py", line 17, in <module>
    from etl.snapshot import snapshot_catalog
  File "/Users/parriagadap/etl/etl/snapshot.py", line 16, in <module>
    from owid.catalog.meta import pruned_json
  File "/Users/parriagadap/etl/lib/catalog/owid/catalog/__init__.py", line 3, in <module>
    from . import utils
  File "/Users/parriagadap/etl/lib/catalog/owid/catalog/utils.py", line 6, in <module>
    import dynamic_yaml
ModuleNotFoundError: No module named 'dynamic_yaml'
```

Cool, besides this dymamic_yaml installation, it is working as we want, at least in my use case. Would you prefer to merge it and then I apply the changes to all this dataset or keep trying before?

**Comment by Marigold** [comment]
> Would you prefer to merge it and then I apply the changes to all this dataset or keep trying before?

I don't think it's worth changing existing datasets (or do you think otherwise?). I'd keep this open until we have a real use case, fine tune it on that and then merge. If you have a dataset that would benefit from this, let me know!

**Pull request merged**
