### PR TITLE
📊 growth: Upload historical GDP datasets (Fariss, Roodman)

### PR DESCRIPTION
**Pull request by paarriagadap**
## Summary by CodeRabbit

- **New Features**
	- Introduced new datasets and snapshots enhancing the garden and meadow datasets with historical GDP, GDP per capita, population, and world product data spanning from 1500 A.D to 2019 C.E.
	- Enhanced data processing capabilities to include country and year information, adjust numerical values (e.g., population in millions, GDP in billions), and standardize column names for improved dataset consistency and usability.
- **Documentation**
	- Added comprehensive metadata for each dataset and snapshot, including data origin, producer, citation, version, license information, and access dates, ensuring users have all necessary context for data usage and citation.

### CODE REVIEW

**Comment by paarriagadap** [comment]
.

**Comment by lucasrodes** [comment]
@paarriagadap
Just checking; is this work still on?

**Comment by paarriagadap** [comment]
@lucasrodes It's on, but paused. I can find to find a way to merge this and continue afterward if it's a problem

**Comment by lucasrodes** [comment]
It's alright if you are still on it. I'm just reviewing PRs, and cleaning if needed.

I find it hard to work on PRs for a long time since they get easily out of sync with master, but that's personal preference.

**Comment by paarriagadap** [comment]
@lucasrodes Yes, in cases like this I rebase and might rebuild the server as well, to avoid those sync problems.

**Pull request closed without merging**
