### PR TITLE
Add fast-track to add datasets from Google Sheets

### PR DESCRIPTION
**Pull request by Marigold**
## Fast-track

Original issue https://github.com/owid/engineering/issues/34

Fast-track is an interactive web app quite similar to Walkthrough. It lets authors store their data and metadata in Google Sheets and import it to ETL and grapher DB with a few clicks in fast-track. It supports country harmonisation, metadata validation, etc. Features that are not implemented yet are mentioned in instructions and gonna be added on-demand.

Here's an [example of the spreadsheet](https://docs.google.com/spreadsheets/d/1ReTohcxpo-dRvnXFzYG4N0YT-HoXh3b6AbG-qIaGTLI/edit?usp=sharing) for nuclear warheads.

To review this, run `poetry install` and then `poetry run fasttrack` and follow instructions. You can either try your own dataset or reuse nuclear warheads from above.

### CODE REVIEW

**Review by pabloarosado — COMMENTED** [review]
This is looking great! I haven't had time to look in detail through the code. But the interface looks neat! So far here are my thoughts:
* How do you add more than one source? Maybe this should be explained in the README or instructions. I suppose you could just put one on top of the other, starting with "short_name". Alternatively, it could be a table, with columns "short_name, name, published_by, ..." and each row is a source.
* I'm wondering if, in variables_meta, an additional column could be "source.short_name". If empty, the sources will be those from the dataset.
* In the template, it would be nice if the variable title was "Variable A" (to signal that it's a human-readable title).
* Shouldn't "publication_year" and "publication_date" also be optional fields in dataset_meta?
* I don't understand what happens with raw data. I'm wondering if, optionally, the download link could be provided, in which cases we would have pretty much everything to create the complete standard snapshot.
* I just followed the steps and, when publishing to web, I see under "Published content and settings" that "Restrict access to the following (GCDL)" is by default unticked. Would it need to be ticked for private datasets? If so, mention it in the README/instructions.
* After pasting the link, the dropdown of existing google sheets still shows AI Index and Nuclear Warheads. I don't know the meaning of that dropdown.
* After submitting, I got this error:
```
Traceback (most recent call last):
  File "/Users/prosado/Documents/owid/repos/etl/.venv/lib/python3.9/site-packages/pywebio/session/threadbased.py", line 86, in main_task
    target()
  File "/Users/prosado/Documents/owid/repos/etl/fasttrack/cli.py", line 60, in <lambda>
    lambda: app(dummy_data=dummy_data),
  File "/Users/prosado/Documents/owid/repos/etl/fasttrack/cli.py", line 79, in app
    data, meta, sheets_url, form = _load_data_and_meta(dummies)
  File "/Users/prosado/Documents/owid/repos/etl/fasttrack/cli.py", line 186, in _load_data_and_meta
    form = FasttrackForm(**form_dict)
  File "/Users/prosado/Documents/owid/repos/etl/fasttrack/cli.py", line 146, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FasttrackForm
commit
  field required (type=value_error.missing)
  ```
  So that's where I'm at :-). I'm excited about the result! I'd also like to know your thoughts on how this would fit with the "slowtrack". Will we end up having lots of fast-track datasets in ETL? If so, will there be an easy way to adapt them?

**Comment by Marigold** [comment]
> I haven't had time to look in detail through the code

Thanks Pablo, much appreciated! Reviewing interface is much more useful to me. The code will change anyway (I'm gonna refactor it as soon as we have something stable in place).

> How do you add more than one source? Maybe this should be explained in the README or instructions. I suppose you could just put one on top of the other, starting with "short_name". Alternatively, it could be a table, with columns "short_name, name, published_by, ..." and each row is a source.

It works exactly like that - every column is separate source. Improved README in the template (README still sucks, gonna improve it over time).

> I'm wondering if, in variables_meta, an additional column could be "source.short_name". If empty, the sources will be those from the dataset.

Great idea, added it.

> Shouldn't "publication_year" and "publication_date" also be optional fields in dataset_meta?

I'm not sure to be honest. Publication year and date are properties of sources or **walden / snapshot metadata**. I thought about adding `snapshot_metadata` where publication year could live, but it would be converted to `source.publication_year` in function `convert_snapshot_metadata` anyway... Anyway, keeping it open, but not adding such complexity yet.

> I don't understand what happens with raw data. I'm wondering if, optionally, the download link could be provided, in which cases we would have pretty much everything to create the complete standard snapshot.

Good idea. What do you think about adding python snippet for accessing both data and metadata through `Snapshot` class? (download link would be unwieldy for private datasets which I assume would be majority in exploration phase)

> I just followed the steps and, when publishing to web, I see under "Published content and settings" that "Restrict access to the following (GCDL)" is by default unticked. Would it need to be ticked for private datasets? If so, mention it in the README/instructions.

I'll mention it. It mustn't be restricted right now (otherwise we'd have to auth to Google first and then access it, still unclear how are we going to do it). ChatGPT said it's highly unlikely that Google would index it and someone could access it. 

> After pasting the link, the dropdown of existing google sheets still shows AI Index and Nuclear Warheads. I don't know the meaning of that dropdown.

Yeah, UI design... I'm gonna improve it. Once you add your dataset it's gonna be displayed in the dropdown so that you don't have to enter your URL next time.

That bug is my fault, forgot to push fix.

> I'd also like to know your thoughts on how this would fit with the "slowtrack". Will we end up having lots of fast-track datasets in ETL? If so, will there be an easy way to adapt them?

I don't think there will be as many datasets. Ideally, authors can use it to create a basic template and commit it to ETL (automatic commit isn't ready yet) and then make updates directly in ETL. The output of fasttrack looks very similar to the output of the walkthrough.

Thanks once again, feedback like this is invaluable.

**Comment by Marigold** [comment]
@pabloarosado I don't think it makes much sense to do thorough code review for this prototype (it might be more useful at later phases after refactoring). More important is whether this version is feature-wise complete enough to be merged and tested by others (on staging). Getting this merged would make building future features easier (like commits or compare that is WIP). I could also keep working on this feature branch, but since this doesn't touch core ETL code or production, I think it's fine to merge it to master. What do you think?

**Review by pabloarosado — APPROVED** [review]
Awesome work!

**Comment by pabloarosado** [comment]
> @pabloarosado I don't think it makes much sense to do thorough code review for this prototype (it might be more useful at later phases after refactoring). More important is whether this version is feature-wise complete enough to be merged and tested by others (on staging). Getting this merged would make building future features easier (like commits or compare that is WIP). I could also keep working on this feature branch, but since this doesn't touch core ETL code or production, I think it's fine to merge it to master. What do you think?

Please, go ahead!

**Pull request merged**
