### PR TITLE
data(sdg): backport SDG dataset from grapher to etl

### PR DESCRIPTION
**Pull request by Marigold**
Now that we have all data from grapher backported, it's time to assemble them into SDG dataset so that anyone can get the data from our Python API instead of manually downloading them from [SDG tracker](https://sdg-tracker.org/). 

SDG dataset in `etl` catalog is created in several steps:

1. Scrape all goal pages from SDG tracker (e.g. https://sdg-tracker.org/inequality) and extract all charts for the goal (identified by `<div class="indicator">`)
2. For every chart look up its variables from table `chart_dimensions` (this needs grapher database)
3. Merge all variables from a single goal into one wide table
4. Create dataset with tables `sustainable_development_goal_[goal number]`

Here is an example of columns from table `sustainable_development_goal_10`

```
indicator_10_1_1__annualized_average_growth_rate_in_per_capita_real_survey_mean_consumption_or_income__bottom_40pct_of_population__pct
indicator_10_2_1__proportion_of_people_living_below_50_percent_of_median_income__pct__si_pov_50mi
indicator_10_3_1__proportion_of_population_reporting_having_felt_discriminated_against__by_grounds_of_discrimination__sex_and_disability__pct__vc_vov_gdsd__both_sexes__no_breakdown_by_disability__all_grounds_or_no_breakdown
indicator_10_4_1__labour_share_of_gdp__pct__sl_emp_gtotl
indicator_10_5_1__liquid_assets_to_short_term_liabilities__pct__fi_fsi_fsls
indicator_10_5_1__net_open_position_in_foreign_exchange_to_capital__pct__fi_fsi_fssno
indicator_10_5_1__non_performing_loans_net_of_provisions_to_capital__pct__fi_fsi_fsknl
indicator_10_5_1__non_performing_loans_to_total_gross_loans__pct__fi_fsi_fsanl
indicator_10_5_1__regulatory_capital_to_assets__pct__fi_fsi_fska
indicator_10_5_1__regulatory_tier_1_capital_to_risk_weighted_assets__pct__fi_fsi_fskrtc
indicator_10_5_1__return_on_assets__pct__fi_fsi_fsera
indicator_10_6_1__proportion_of_members_of_developing_countries_in_international_organizations__by_organization__pct__sg_int_mbrdev__african_development_bank
indicator_10_6_1__proportion_of_members_of_developing_countries_in_international_organizations__by_organization__pct__sg_int_mbrdev__asian_development_bank
indicator_10_6_1__proportion_of_members_of_developing_countries_in_international_organizations__by_organization__pct__sg_int_mbrdev__financial_stability_board
indicator_10_6_1__proportion_of_members_of_developing_countries_in_international_organizations__by_organization__pct__sg_int_mbrdev__inter_american_development_bank
indicator_10_6_1__proportion_of_members_of_developing_countries_in_international_organizations__by_organization__pct__sg_int_mbrdev__international_bank_for_reconstruction_and_development
indicator_10_6_1__proportion_of_members_of_developing_countries_in_international_organizations__by_organization__pct__sg_int_mbrdev__international_finance_corporation
indicator_10_6_1__proportion_of_members_of_developing_countries_in_international_organizations__by_organization__pct__sg_int_mbrdev__international_monetary_fund
indicator_10_6_1__proportion_of_members_of_developing_countries_in_international_organizations__by_organization__pct__sg_int_mbrdev__un_economic_and_social_council
indicator_10_6_1__proportion_of_members_of_developing_countries_in_international_organizations__by_organization__pct__sg_int_mbrdev__un_general_assembly
indicator_10_6_1__proportion_of_members_of_developing_countries_in_international_organizations__by_organization__pct__sg_int_mbrdev__un_security_council
indicator_10_6_1__proportion_of_members_of_developing_countries_in_international_organizations__by_organization__pct__sg_int_mbrdev__world_trade_organisation
indicator_10_7_2__countries_with_migration_policies_to_facilitate_orderly__safe__regular_and_responsible_migration_and_mobility_of_people__by_policy_domain__1__requires_further_progress__2__partially_meets__3__meets__4__fully_meets__sg_cpa_migrs__all_domains
indicator_10_7_3__total_deaths_and_disappearances_recorded_during_migration__number__sm_dth_migr
indicator_10_7_4__number_of_refugees_per_100_000_population__by_country_of_origin__per_100_000_population__sm_pop_refg_or
indicator_10_a_1__proportion_of_tariff_lines_applied_to_imports_with_zero_tariff__pct__tm_trf_zero__total_or_no_breakdown
indicator_10_b_1__total_assistance_for_development__by_donor_countries__millions_of_current_united_states_dollars__dc_trf_totdl
indicator_10_b_1__total_assistance_for_development__by_recipient_countries__millions_of_current_united_states_dollars__dc_trf_totl
indicator_10_c_1__average_remittance_costs_of_sending_dollar200_for_a_sending_country_as_a_proportion_of_the_amount_remitted__pct__si_rmt_cost_snd
```

Once we have it in catalog, one will be able to visualize indicator 10.5.1 with
```python
sdg_dataset = Catalog().find(dataset="sustainable_development_goals").load()
t = sdg_dataset['sustainable_development_goal_10']

t = t[[c for c in t.columns if c.startswith('indicator_10_5_1')]].loc['Poland'].dropna(how='all')

# use titles instead of underscored short names of variables
t.rename(columns={c: t[c].metadata.title for c in t.columns}).iplot()
```

@spoonerf what do you think? Is this automatic approach good enough for the first iteration or should I jump right into manual curation (any idea how should it look then)?

Additional notes:
* I wanted to use [spreadsheet](https://docs.google.com/spreadsheets/d/1n0UrpKKS2JVcXSmth_QVYLThlWev6pzEiHP7HaIq9BY/edit#gid=1284188229) with all charts and variables at first, but a lot of it was out of date so scraping was easier
* ~~Not all indicators in SDG tracker use `<div class="indicator">`, we should fix that~~
* Currently one table contains **all variables for a goal**, but we can also make it **one table for target**

### CODE REVIEW

**Comment by spoonerf** [comment]
Hi @Marigold 

Sorry for the delay in getting back to you - this looks great! I can go through and fix the `<div class="indicator">` issue today.

I think one table per goal is good. No idea if this would be hard or straightforward but how difficult would it be to make a table per country? Or even per country per goal?

**Comment by Marigold** [comment]
> Sorry for the delay in getting back to you - this looks great! I can go through and fix the <div class="indicator"> issue today.

No worries, I can do it myself, just wanted to get a confirmation that I have the right direction.

> I think one table per goal is good. No idea if this would be hard or straightforward but how difficult would it be to make a table per country? Or even per country per goal?

Interesting, I've always thought we'd want as few tables as possible and have all countries in a single dataframe to be comparable. Perhaps this is not the case for SDG and one would want to compare goals for a country instead? We can also create two datasets `sustainable_development_goals_by_country` and `sustainable_development_goals_by_goal`, but I'm not sure how useful is that since everyone can easily reshape those datasets locally. What do you think?

**Comment by spoonerf** [comment]
Ah okay, I think you're right. I think it would be good to have SDG variables available by country (and/or goal) somewhere within the SDG Tracker, but as you say it would be straightforward to create a script that creates those files rather than having them already made in the etl. In general would we always want to have fewer tables in the etl? (Sorry still trying to get my head around how the etl works)

**Comment by Marigold** [comment]
Ok then, I'll leave it as it is and if we find we need it rather by country than goal we can change it in the future.

> In general would we always want to have fewer tables in the etl? (Sorry still trying to get my head around how the etl works)

Generally yes, but it depends as always. Every table is a dataframe, so if you find yourself concatenating a lot of tables then you should have created fewer of them and if you find yourself working with a huge dataframe with unrelated columns then you should have created more of them. Performance wise it doesn't matter (unless you'd be creating hundreds of them)

**Comment by Marigold** [comment]
This is good to go now from the technical side.

**Comment by Marigold** [comment]
> Looks good - in the notebook the first paragraph still talks about the spreadsheet but this is no longer accurate, right?

Fixed

> Is the backport:// syntax still the way to do it? I seem to remember that for the main grapher backport this is now done differently and not enumerated in the dag per se but this one is maybe different?

Main grapher backport generates these `backport://` steps dynamically (with `--backport` flag) and adds them into `dag.yml`. So a snapshot of dag after adding dynamic backport steps would look like this

```
data://garden/sdg/latest/sdg:
  - backport://backport/owid/latest/dataset_943_sexual_violence__unicef__2017:
  - ...

backport://backport/owid/latest/dataset_943_sexual_violence__unicef__2017:
  - walden://backport/owid/latest/dataset_943_sexual_violence__unicef__2017
```

**Pull request merged**
