### PR TITLE
✨ war: checks and documentation on regions

### PR DESCRIPTION
**Pull request by lucasrodes**
_(some information here relies on https://github.com/owid/owid-issues/issues/446#issuecomment-1665467376)_
# PR short summary
No need for very detailed revision, I have mostly modified documentation in the `dataset.description` fields in metadata, and in the top-file docstring of some python scripts.

Besides this, I have re-organised how some regions are named. E.g., we use "Asia and Oceania" instead of "Asia".

---
# Details

Which regions are used in each dataset? This PR tries to improve the documentation on this for each data source. 

## UCDP and PRIO
Both sources report data for the same regions: Africa, Americas, Asia and Oceania, Europe, Middle East.

Note: Originally, they referred to "Asia and Oceania" as "Asia" solely, but we have renamed it because countries in Oceania are included (see page 45 https://ucdp.uu.se/downloads/ged/ged231.pdf).

Based on codes from Gleditsch ([states](http://ksgleditsch.com/data/iisystem.dat) and [micro-states](http://ksgleditsch.com/data/microstatessystem.dat)):

- Americas: `2-199`
- Europe: `200-399`
- Africa: `400-626`
- Middle East: `630-699`
- Asia and Oceania: `700-999`

## COW Wars, COW MID
Relies on codes from Correlates of War ([page](https://correlatesofwar.org/data-sets/state-system-membership/), file "states2016.csv").

- Americas: `2-165`
- Europe: `200-399`
- Africa: `402-626`
- Middle East: `630-698`
- Asia and Oceania: `700-999`

## MIC
Relies on codes from Correlates of War ([page](https://correlatesofwar.org/data-sets/state-system-membership/), file "states2016.csv"). This is very similar to how we encode in COW MID, as the MIC dataset builds around that dataset.

- Americas: `2-165`
- Europe: `200-399`
- Africa: `402-626`
- Middle East: `630-698`
- Asia and Oceania: `700-999`

## Brecke
Relies on codes from Correlates of War ([page](https://correlatesofwar.org/data-sets/state-system-membership/), file "states2016.csv"). Some details on countries in regions can be found on page 10 of Brecke's 1999 paper [Violent Conflicts 1400 A.D. to the Present in Different Regions of the World](https://bpb-us-w2.wpmucdn.com/sites.gatech.edu/dist/1/19/files/2018/09/Brecke-PSS-1999-paper-Violent-Conflicts-1400-AD-to-the-Present.pdf).

- Africa (from East & South Africa + North Africa + West & Central Africa): `402-626`
- Americas (from North America + Central America + the Caribbean and South America): `2-165`
- Asia and Oceania (from Central Asia + East Asia + South Asia + Southeast Asia): `700-990`
- Europe (from Eastern Europe + Western Europe): `200-395`
- Middle East (from Arabian Peninsula and Iran west to Syria): `630-698`

## Project Mars
Reports data on more granular regions. Relies on codes from Correlates of War ([page](https://correlatesofwar.org/data-sets/state-system-membership/), file "states2016.csv").

- Americas (North America + Latin America): `2-165`
- Europe (Western Europe + Eastern Europe): `200-395`
- Sub-Saharan Africa: `402-420`, `433-434`, `437-482`, `484-517`, `540-591`
- North Africa and the Middle East: `432`, `435-436`, `483`, `520-531`, `600-698`
- Asia and Oceania: `700-990`

### CODE REVIEW

**Comment by bastianherre** [comment]
Hey @lucasrodes!

Thanks for creating this nice overview!

For COW and MIC, I wonder whether we should combine Asia and Oceania for all indicators. That would make comparisons across sources easier. Or would that create more problems?

For Brecke, I would sort Turkey (#640) into the Middle East. That would be much more in line with how the country is commonly understood.

For Project Mars, I lean towards combining North America and South America into Americas. That would make it easier to compare to other sources — and I don't know how insightful a regional overview of a region consisting of just the US and Canada is.

We could even consider combining Western and Eastern Europe. I think here the regional overviews are more insightful — but it again would make comparing across sources easier. Could it be you accidentally switched the codes for Western and Eastern Europe? Additionally, I would code Austria-Hungary (#300) as Western Europe.

Coding 'North Africa and Middle East' is tricky. How did you decide to code # 432, 435-436, 483, and 520-531? Are you basing this on the region Lyall coded for the conflicts in which these countries were involved?

**Comment by lucasrodes** [comment]
Thanks for your feedback, @bastianherre. I've included some comments below on your points.


> For COW and MIC, I wonder whether we should combine Asia and Oceania for all indicators. That would make comparisons across sources easier. Or would that create more problems?

From a technical perspective, this is totally doable. Unless specified otherwise, I'll combine these regions in the data.


> For Brecke, I would sort Turkey (# 640) into the Middle East. That would be much more in line with how the country is commonly understood.

From [their definition](https://bpb-us-w2.wpmucdn.com/sites.gatech.edu/dist/1/19/files/2018/09/Brecke-PSS-1999-paper-Violent-Conflicts-1400-AD-to-the-Present.pdf) (page 10), it was unclear to me if Turkey belonged to Middle East: "Middle East (Iran west to Syria and Arabian peninsula)". I assumed Turkey to be outside of this definition.

After checking the data itself, and the conflicts that involved Turkey (there are ~260), I found out that in 187 (70%) of them the conflict was assigned to Eastern Europe (37 were assigned to Middle East, 19 to North Africa, etc.). Therefore I ended up assigning Turkey to Eastern Europe.


> For Project Mars, I lean towards combining North America and South America into Americas. That would make it easier to compare to other sources — and I don't know how insightful a regional overview of a region consisting of just the US and Canada is.


Totally, happy to change this for Project Mars.


> We could even consider combining Western and Eastern Europe. I think here the regional overviews are more insightful — but it again would make comparing across sources easier. Could it be you accidentally switched the codes for Western and Eastern Europe? Additionally, I would code Austria-Hungary (#300) as Western Europe.

- I think combining East + West makes sense for comparability purposes. Plus, I think that from a technical standpoint it is perfectly doable.
- Regarding the codes for East/West Europe, I switched the codes accidentally! Fixed it
- Since we will be combining East + West, I guess no need to assign AH to West.

> Coding 'North Africa and Middle East' is tricky. How did you decide to code # 432, 435-436, 483, and 520-531? Are you basing this on the region Lyall coded for the conflicts in which these countries were involved?

That was indeed very tricky. I based the selection precisely on what you mention, the participants in the wars. Although a participant may participate in conflicts in different regions, I tried to make sense of (i) the region the state participated in the most, (ii) name of the conflict (sometimes gives hints on the region too).

**Comment by bastianherre** [comment]
Hey Lucas! Thanks a lot for making all these changes! I only still think we shouldn't put Turkey into Europe.

The datasets other than Brecke don't do it, so us doing it would make it more difficult to compare sources.

And I think looking at the region of the countries Turkey has most often fought with is misleading — the Ottoman Empire for a long time covered large parts of the Middle East, so its conflicts there were internal, while it never had firm control over territories in Southeastern Europe, and so had many interstate conflicts there.

**Comment by lucasrodes** [comment]
I see, thanks! Just to confirm: We are still OK with the region assignment that is done by Project Mars (i.e. assigning most of the conflicts where Turkey/Ottoman empire has participated to Europe, and others to the other regions).

**Comment by bastianherre** [comment]
Yes, I would say so — this is because now, we are assigning countries to regions. Before, we were assigning conflicts to regions.

For example, the US clearly is in the Americas, even if its war with Japan during World War II was mostly fought in Asia.

**Comment by bastianherre** [comment]
Hey @lucasrodes!

Thanks for this neat overview! It's encouraging to see most sources working out very well.

As for Project Mars, I see a case for using the International Systems Dataset (ISD) instead of CoW. I like your suggestion of asking Jason Lyall himself and have emailed him.

As for Brecke, could you produce the list of potential states only for the years since about 1800? That would give us a better sense of the scope, as we only have state system data since then. But I increasingly lean towards using ISD here.

As for whether we should standardize non-state conflicts, this is a very good question.

I agree that it makes less sense than for the other conflict types, as no state is involved. We could standardize by the world/region population — but this makes the indicator quite difficult to understand, especially compared to the other conflict types.

I would therefore prefer to use the number of countries as a rough indicator for the number of people and calculate the conflict rate this way. And for death rates, we can then standardize by population across the board, as the resulting indicators are more intuitive.

**Comment by lucasrodes** [comment]
I've implemented all the proposed changes by Bastian:

- Clarify which definitions of regions for each data source.
- Harmonize regions as much as possible:
  - Use `Asia and Oceania` instead of each (`Asia` and `Oceania`) separately. (COW and MIC, and possible others)
  - Combine `Eastern Europe` and `Western Europe` into `Europe`.
  - Combine `North America` and `Latin America` into `Americas`. (Mars)
  - Assign the Middle East to Turkey. (Brecke)

---

I will follow-up on https://github.com/owid/etl/pull/1586#issuecomment-1719711066 in a future PR.

**Review by spoonerf — APPROVED** [review]
Looks good - very cool to see the Jinja templates. Just noticed a couple of typos but otherwise metadata looks solid.

**Pull request merged**
