### PR TITLE
chore: switch from flake8 to ruff

### PR DESCRIPTION
**Pull request by larsyencken**
The ruff linter is a much faster linter written in rust.

### CODE REVIEW

**Comment by Marigold** [comment]
This looks good, @larsyencken should I review it?

**Comment by larsyencken** [comment]
This wasn't urgent, closing it.

**Comment by Marigold** [comment]
How far did you get @larsyencken? I'm having minor issues locally with isort and flake8 and this might perhaps solve them both.

**Comment by Marigold** [comment]
Speedup:

* isort -> ruff: 7.8s -> 1.6s
* black -> ruff: 6s -> 1.8s

**Comment by larsyencken** [comment]
Nice! What's the best way to get it working in VSCode? It's a pet hate of mine when CI and editor lint differently.

**Comment by Marigold** [comment]
Sorry! It was a WIP comment and I accidentally submitted it. I'm preparing more thorough overview (plus of course how to set it up in VSCode). It looks pretty promising so far!

**Comment by Marigold** [comment]
@pabloarosado here's a [summary](https://github.com/owid/etl/pull/1017#issuecomment-1818665033) of the proposed change. What do you think, is it worth it or would you rather stick to our existing tools?

**Review by pabloarosado — APPROVED** [review]
Looks good, and the speed up is going to be very much appreciated! I haven't tried it, have you noticed any major change in how files are formatted? If not, I'm happy to switch to ruff.

**Comment by larsyencken** [comment]
> Looks good, and the speed up is going to be very much appreciated! I haven't tried it, have you noticed any major change in how files are formatted? If not, I'm happy to switch to ruff.

Ruff tries to format identically to Black on pre-blackened code, though on code that hasn't been auto-formatted it might make a different choice. https://docs.astral.sh/ruff/formatter/#black-compatibility

**Review by larsyencken — COMMENTED** [review]
Looks good, let's do it 🚀

**Pull request merged**
