### PR TITLE
📊 climate: Era-5 -June data

### PR DESCRIPTION
**Pull request by veronikasamborska1994**

### CODE REVIEW

**Comment by veronikasamborska1994** [comment]
@Marigold hii! any chance you could take a look at why this is failing? seems to be an issue with dependencies possibly related to the recent changes you've made

**Comment by Marigold** [comment]
@veronikasamborska1994 I reran snapshot from the staging server, which seems to have fixed it. Just installing `h5netcdf` library it was complaining about wasn't enough. Let's see what happens at next update.

**Comment by veronikasamborska1994** [comment]
> @veronikasamborska1994 I reran snapshot from the staging server, which seems to have fixed it. Just installing `h5netcdf` library it was complaining about wasn't enough. Let's see what happens at next update.

@Marigold yeah I tried that too and didn't work.. happy for me to merge this one then?

**Review by Marigold — APPROVED** [review]
Looks good!

**Pull request merged**
