### PR TITLE
🐛 Fix detect changed datasets, and update bullfighting laws

### PR DESCRIPTION
**Pull request by pabloarosado**
* The goal of this PR is to fix https://github.com/owid/etl/issues/2733
* To test it, I updated bullfighting laws, given that recently it has been banned in Colombia.

NOTE: I don't fully understand the logic behind how staging servers are updated on commit. I have tested that indicator upgrader shows the right new dataset ("bullfighting laws") both on local wizard and on [the corresponding staging server](http://staging-site-fix-detect-changed-datasets/etl/wizard/). But I will test it again on a new branch, after merging.

### CODE REVIEW

**Comment by pabloarosado** [comment]
The easiest way to check that it works is from the CLI, running `poetry run etl d map-datasets` should print only the old and new versions of the `bullfighting_laws` dataset. I have done that locally (both pointing to my local grapher and to staging) and I have also done the same thing directly from staging.
Additionally, if you go to the wizard indicator upgrader, the dataset selected by default as "New dataset" should be "Bullfighting laws". I've checked that this happens both in local wizard and staging.

**Comment by lucasrodes** [comment]
hi Pablo, I just checked on Wizard and it is not working for me.

1. Run Wizard `etlwiz`
2. Go to http://localhost:8053 then to "Indicator Upgrader".
3. For me, pre-selected new dataset is "Global Health Estimates"


This is the log after running `etlwiz`:

```
etlwiz
2024-06-05 11:56:49.497 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8053
  Network URL: http://192.168.0.222:8053
  External URL: http://93.176.168.109:8053

2024-06-05 11:56:58 [warning  ] ENV file doesn't connect to production DB, comparing against `staging-site-master`.
called DB for state, got: approved
Showing diff, state: True False False
2024-06-05 11:57:15 [error    ] No candidate in steps_df was found! Working with old datasets (non-ETL)?
2024-06-05 11:57:15 [error    ] No candidate in steps_df was found! Working with old datasets (non-ETL)?
2024-06-05 11:57:15 [error    ] No candidate in steps_df was found! Working with old datasets (non-ETL)?
2024-06-05 11:57:15 [error    ] No candidate in steps_df was found! Working with old datasets (non-ETL)?
2024-06-05 11:57:15 [warning  ] pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy. category=UserWarning filename=/home/lucas/repos/etl/etl/db.py lineno=245
```

https://github.com/owid/etl/assets/18101289/aac47b54-a961-4b85-8b0e-fab78de9963c

**Comment by lucasrodes** [comment]
I've also tested `poetry run map-datasets ` and get an error:

```
poetry run etl d map-datasets
2024-06-05 12:02:54 [error    ] No candidate in steps_df was found! Working with old datasets (non-ETL)?
2024-06-05 12:02:54 [error    ] No candidate in steps_df was found! Working with old datasets (non-ETL)?
2024-06-05 12:02:54 [error    ] No candidate in steps_df was found! Working with old datasets (non-ETL)?
2024-06-05 12:02:54 [error    ] No candidate in steps_df was found! Working with old datasets (non-ETL)?
Based on the changes committed to the current git branch, 1 grapher dataset pairs need to be mapped.

2024-06-05 12:02:54,065 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lucas/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/repos/etl/.venv/lib/python3.11/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/lucas/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/repos/etl/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/repos/etl/apps/utils/map_datasets.py", line 199, in cli
    print(f'[{change["old"]["id"]}] {change["old"]["name"]}')
              ~~~~~~^^^^^^^
KeyError: 'old'
```

**Comment by pabloarosado** [comment]
Hey @lucasrodes thanks for checking. Can you please try again? I don't understand why you get those issues, but hopefully with my latest changes, we should get consistent results.

**Comment by lucasrodes** [comment]
@pabloarosado thanks for working on this. I just ran the method and it seems to be working now.

```
✗ poetry run etl d map-datasets                                      
2024-06-05 15:29:42 [error    ] No candidate in steps_df was found! Working with old datasets (non-ETL)?
Based on the changes committed to the current git branch, 1 grapher dataset pairs need to be mapped.

[6216] Bullfighting laws
    Step: data://grapher/animal_welfare/2023-09-05/bullfighting_laws
[6545] Bullfighting laws
    Step: data://grapher/animal_welfare/2024-06-04/bullfighting_laws
```

I tried it in **Indicator upgrader** in wizard and seems to be working too!

**Comment by lucasrodes** [comment]
There are some scenarios where I am not sure how the tool will behave. I'm just unsure about relying on git, but I guess we can just try and note down the instances where it does not work.

From the top if my mind, I am thinking of the scenario: Suppose someone adds now a new dataset in master. Will the diff between branches mess things? Does it make a difference if this branch is up to date with latest master changes (i.e. we've run `git merge master`)

**Comment by pabloarosado** [comment]
Yeah, I'm also trying to figure out if the current logic is robust. I think that what we usually want is to compare the *local current branch* (with committed or possibly uncommited changes) with the *remote master branch*. I just changed the code accordingly.
I'm thinking that, now that I'm here, I could see if it would be possible to have, optinally, a "deep" list of affected datasets. In other words, instead of listing only the newly created grapher datasets, we could list all grapher datasets (new or existing) affected by current changes. This logic could eventually be used in chart diff too.

**Comment by pabloarosado** [comment]
OK, then let's do that in a different PR. Do you approve this one for merging?

**Pull request merged**
