### PR TITLE
🎉 Docs for ChatGPT tool for filling out metadata automatically

### PR DESCRIPTION
**Pull request by veronikasamborska1994**

### CODE REVIEW

**Comment by lucasrodes** [comment]
Thanks for working on this, @veronikasamborska1994!

Some minor notes:
### Adding the new entry to `mkdocs.yml`
I forgot to share this entry [in our docs][(https://docs.owid.io/projects/etl/dev/docs/), which explains how to add a new entry. Note that you need to add the new file (`architecture/metadata/metadata_chatgpt_update.md`) to the `mkdocs.yml` file. I've added now so it shows up.

You can preview the documentation from your local machine:

```bash
mkdocs serve
```

### Structure of `metadata_chatgpt_update.md`
I have slightly remixed the file so it is a bit easier to follow. I've basically merged the sections "Main functionality" and "Usage" into a single one.

I would encourage you to replace the fist bit of the doc:

> This tool, accessible via the command etl-metagpt, is designed to update metadata files using OpenAI's GPT model. It currently supports two types of metadata files: 'snapshot' and 'grapher'.

This is the first sentence someone will read, and it does not summarise what the tool does or why it is useful. I suppose its purpose is to improve the metadata files by completing some fields or updating files with out-of-date metadata standards. I'd suggest adding a line like this one and maybe later mention that it uses OpenAI's GPT model and that it supports two metadata files.

**Review by lucasrodes — CHANGES_REQUESTED** [review]
see my comment above

**Comment by veronikasamborska1994** [comment]
> Thanks for working on this, @veronikasamborska1994! I'm excited to use this tool.
> 
> Some minor notes:
> 
> ## Adding the new entry to `mkdocs.yml`
> I forgot to share this entry [in our docs](https://docs.owid.io/projects/etl/dev/docs/), which explains how to add a new entry. Note that you need to add the new file (`architecture/metadata/metadata_chatgpt_update.md`) to the `mkdocs.yml` file. I've added now so it shows up.
> 
> You can preview the documentation from your local machine:
> 
> ```shell
> mkdocs serve
> ```


ah thank you! 👍 I was going to ask how to fix this so thanks for spotting this right away :)

**Review by lucasrodes — APPROVED** [review]
LGTM!

**Comment by lucasrodes** [comment]
@veronikasamborska1994 It looks like the environment variable `OPENAI_API_KEY` is needed for this to work properly. Could we have a small section on the docs on how to get it? Fine if it is just 3 sentence long with couple of links to OpenAI's site.

**Comment by veronikasamborska1994** [comment]
> @veronikasamborska1994 It looks like the environment variable `OPENAI_API_KEY` is needed for this to work properly. Could we have a small section on the docs on how to get it? Fine if it is just 3 sentence long with couple of links to OpenAI's site.

good point!!! added it now :)

**Pull request merged**
